# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development

on:
  push:
    branches: [ master ]

jobs:
  test-deployment:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm install --global yarn
      - run: yarn install
      - run: yarn run build
        env:
          CI: false
      - run: copy C:\\Users\\Administrator\\Desktop\\SSL\\web.config C:\\inetpub\\wwwroot\\DevLMSv3\\LMSv3FrontEnd\\LMSV3FRONTEND\\LMSV3FRONTEND\\build
      - run: copy C:\\Users\\Administrator\\Desktop\\SSL\\web.config C:\\inetpub\\wwwroot\\CICD\\v3-dev\\10.2-dev\\LMSV3FRONTEND\\LMSV3FRONTEND\\build
      
